version: "3"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts:/scripts
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

volumes:
  postgres:
    external: true